services:

  # Nextcloud Application - Multiple replicas for HA
  app:
    image: nextcloud:production-fpm-alpine
    container_name: nextcloud-app
    restart: unless-stopped
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=mariadb
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${TRUSTED_DOMAINS}
      - REDIS_HOST=redis
      - REDIS_HOST_PORT=6379
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
      - OBJECTSTORE_S3_BUCKET=${S3_BUCKET}
      - OBJECTSTORE_S3_KEY=${S3_ACCESS_KEY}
      - OBJECTSTORE_S3_SECRET=${S3_SECRET_KEY}
      - OBJECTSTORE_S3_REGION=${S3_REGION}
      - OBJECTSTORE_S3_HOST=${S3_ENDPOINT}
      - OBJECTSTORE_S3_PORT=${S3_PORT}
      - OBJECTSTORE_S3_SSL=${S3_SSL}
      - OBJECTSTORE_S3_USEPATH_STYLE=true
      - PHP_MEMORY_LIMIT=1024M
      - PHP_UPLOAD_LIMIT=10G
      - APACHE_DISABLE_REWRITE_IP=1
      - TRUSTED_PROXIES=${TRUSTED_PROXIES}
      - OVERWRITEPROTOCOL=https
      - OVERWRITEHOST=${DOMAIN_NAME}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_DOMAIN=${MAIL_DOMAIN}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_AUTHTYPE=${SMTP_AUTHTYPE}
      - SMTP_NAME=${SMTP_NAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    volumes:
      - nextcloud-data:/var/www/html
      - ./config/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      - ./config/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini:ro
      - ./config/nextcloud/config.php:/var/www/html/config/config.php:ro
      - ./logs/nextcloud:/var/log/nextcloud
    networks:
      - shared
      - default
    depends_on:
      - mariadb
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/status.php"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  web:
    image: nginx:alpine
    container_name: nextcloud-nginx
    restart: unless-stopped
    volumes:
      - nextcloud-data:/var/www/html:ro
      - ./config/nginx/nextcloud.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - shared
      - default

  mariadb:
    image: mariadb:10.11
    container_name: nextcloud-mariadb
    restart: unless-stopped
    command: >
      --transaction-isolation=READ-COMMITTED
      --binlog-format=ROW
      --innodb-file-per-table=1
      --skip-innodb-read-only-compressed
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --max-connections=512
      --innodb-buffer-pool-size=1G
      --innodb-log-file-size=256M
      --innodb-flush-log-at-trx-commit=2
      --innodb-flush-method=O_DIRECT
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./config/mariadb/my.cnf:/etc/mysql/conf.d/nextcloud.cnf:ro
      - ./backups/mariadb:/backups
      - ./logs/mariadb:/var/log/mysql
    networks:
      - default
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  redis:
    image: redis:7-alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    command: >
      redis-server 
      --requirepass ${REDIS_PASSWORD}
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
      --appendonly yes
      --appendfsync everysec
    volumes:
      - redis-data:/data
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./logs/redis:/var/log/redis
    networks:
      - default
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  cron:
    image: nextcloud:production-fpm-alpine
    container_name: nextcloud-cron
    restart: unless-stopped
    volumes:
      - nextcloud-data:/var/www/html
      - ./config/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    entrypoint: /cron.sh
    depends_on:
      - mariadb
      - redis
    networks:
      - default
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: nextcloud-elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - ./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./logs/elasticsearch:/usr/share/elasticsearch/logs
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  prometheus:
    image: prom/prometheus:latest
    container_name: nextcloud-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - default
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: nextcloud-node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - default
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  db-backup:
    image: mariadb:10.11
    container_name: nextcloud-db-backup
    restart: "no"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./backups/mariadb:/backups
      - ./scripts/backup.sh:/backup.sh:ro
    entrypoint: /backup.sh
    depends_on:
      - mariadb
    networks:
      - default
    profiles:
      - backup

  watchtower:
    image: containrrr/watchtower
    container_name: nextcloud-watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 2 * * *
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${WATCHTOWER_EMAIL_FROM}
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=${WATCHTOWER_EMAIL_TO}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${SMTP_HOST}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=${SMTP_PORT}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${SMTP_NAME}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${SMTP_PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

volumes:
  nextcloud-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/nextcloud/data
  mariadb-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/nextcloud/mariadb
  redis-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/nextcloud/redis
  elasticsearch-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/nextcloud/elasticsearch
  prometheus-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/nextcloud/prometheus

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
  shared:
    external: true
