cluster.name: nextcloud-cluster
node.name: nextcloud-es-node
path.logs: /usr/share/elasticsearch/logs
path.data: /usr/share/elasticsearch/data
network.host: 0.0.0.0
http.port: 9200

xpack.security.enabled: true
xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.key: certs/es.key
xpack.security.http.ssl.certificate: certs/es.crt
xpack.security.http.ssl.certificate_authorities: certs/ca.crt