---
# config/prometheus/nextcloud_alerts.yml
# Alerting rules for Nextcloud monitoring

groups:
  - name: nextcloud.rules
    rules:
      - alert: NextcloudDown
        expr: up{job="nextcloud"} == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Nextcloud instance is down"
          description: "Nextcloud has been down for more than 5 minutes."

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is above 90% for more than 10 minutes."

      - alert: HighDiskUsage
        expr: (node_filesystem_size_bytes{fstype!="tmpfs"} - node_filesystem_free_bytes{fstype!="tmpfs"}) / node_filesystem_size_bytes{fstype!="tmpfs"} > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High disk usage detected"
          description: "Disk usage is above 80%."

      - alert: DatabaseDown
        expr: up{job="mariadb"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "MariaDB is down"
          description: "MariaDB has been down for more than 2 minutes."

      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Redis is down"
          description: "Redis has been down for more than 2 minutes."