services:
  web:
    image: nginx:alpine
    container_name: nextcloud-nginx
    restart: unless-stopped
    volumes:
      - nextcloud-data:/var/www/html:ro
      - ./config/nginx/nextcloud.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - shared
      - default