services:
  db-backup:
    image: mariadb:10.11
    container_name: nextcloud-db-backup
    restart: "no"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./backups/mariadb:/backups
      - ./scripts/backup.sh:/backup.sh:ro
    entrypoint: /backup.sh
    depends_on:
      - mariadb
    networks:
      - default
    profiles:
      - backup